language: rust
rust: nightly
script: make test

cache:
  - cargo
  - directories: bin

services:
  - postgresql

env:
  global:
    - DATABASE_URL="postgres://postgres@localhost:5432/meals"

before_script:
  - psql -c 'create database meals;' -U postgres
  - export ROCKET_DATABASES="{ meals = { url = \"$DATABASE_URL\" } }"